### PR TITLE
Add Terraform check support

### PR DESCRIPTION
**Pull request by inFocus7**
#90
- Add Terraform group checks
- Add information on creating/testing new groups locally in contributing docs

### CODE REVIEW

**Comment by kaplanelad** [comment]
Hey, @inFocus7,
 Is the PR ready?

**Comment by inFocus7** [comment]
Hey! It's 98% ready. The only issue i have is not knowing how to set up the Regex to see if the -dry-run flag is missing

**Comment by kaplanelad** [comment]
it will be easier for your to check your patterns by running the command:
```bash
cargo run -- pre-command --command "{YOUR COMMAND`}"
```
This will run shellfirm on your given command (without running the command, of course)

**Comment by kaplanelad** [comment]
Hey @inFocus7, How can I help you to finish this PR? I really think the terraform is really necessary

**Comment by kaplanelad** [comment]
Hey @inFocus7,
Do you want to give me an example of your regex problem? i can help you to finish this PR
regex example: ____
prompt command: ____
ignore prompt command: ____

**Pull request closed without merging**
